Repository cancervariants/disease-normalization, pull requests merged in 2024-12, with the labels that each got.

#211 fix: handle mondo xref annotation changes
  pyproject.toml
  src/disease/etl/mondo.py
  tests/data/mondo/mondo_20230912.obo
  tests/data/mondo/mondo_20241203.obo
  tests/data/oncotree/oncotree_20211102.json
  tests/unit/test_merge.py
  tests/unit/test_mondo.py
  tests/unit/test_oncotree.py
  tests/unit/test_query.py
Labels: priority:low

#210 feat!: update models to vrs 2.0.0 community review ballot
  pyproject.toml
  src/disease/query.py
  src/disease/schemas.py
  tests/unit/test_query.py
Labels: enhancement, priority:medium, build

#215 feat!: use preferred formats for `MappableConcept.mappings`
  src/disease/query.py
  src/disease/schemas.py
  tests/unit/test_query.py
Labels: enhancement, priority:high

#216 feat!: remove `normalized_id` and leverage `MappableConcept.primaryCode`
  README.md
  docs/source/index.rst
  docs/source/install.rst
  src/disease/query.py
  src/disease/schemas.py
  tests/unit/test_endpoints.py
  tests/unit/test_query.py
Labels: enhancement, priority:high
